import streamlit as st


def show_tutorial():
    st.title("📖 Tutorial")
    st.markdown("Welcome! This guide will help you get personalized movie recommendations in just a few steps.")

    st.divider()

    # Quick Start Section
    st.header("🚀 Quick Start")

    st.markdown("""
    **Get recommendations in 5 simple steps:**

    1️⃣ **Set the Magic Number** — This randomizes which movies you'll see. Change it to discover different films!

    2️⃣ **Choose How Many Movies to Rate** — Select between 6-20 movies using the slider.

    3️⃣ **Select Your Favorite Genres** — Filter movies by genres you enjoy (Action, Comedy, Drama, etc.)

    4️⃣ **Rate the Movies** — Click the checkbox to reveal movies, then rate them from 1-5. Use 0 if you haven't seen a movie.

    5️⃣ **Get Your Recommendations** — Click "RECOMMEND MOVIES!" and let our AI find your next favorite film!
    """)

    st.info("💡 **Tip:** The more movies you rate honestly, the better your recommendations will be!")

    st.divider()

    # Page Navigation Section
    st.header("📑 Pages Overview")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("""
        **🎬 Recommendation**

        The main page where you rate movies and receive personalized suggestions.
        """)

        st.markdown("""
        **⚙️ Tune the Model**

        Adjust hyperparameters for advanced users:
        - Number of iterations
        - Number of features  
        - Optimizer type
        """)

    with col2:
        st.markdown("""
        **📊 Explore**

        View statistics about the movie database:
        - Top rated movies
        - Genre distributions
        - Rating trends over time
        """)

        st.markdown("""
        **📚 References**

        Credits, data sources, and acknowledgments.
        """)

    st.divider()

    # Understanding Results Section
    st.header("📈 Understanding Your Results")

    st.markdown("""
    After the model trains, you'll see two tables:

    | Table | What It Shows |
    |-------|---------------|
    | **Your Ratings vs Predictions** | Compares your actual ratings to what the model predicted. Closer values = better model fit. |
    | **Recommended Movies** | Top 10 movies the model thinks you'll enjoy, sorted by predicted rating. |
    """)

    st.warning("⚠️ **Large gaps** between your ratings and predictions? Try increasing iterations in 'Tune the Model'.")

    st.divider()

    # Advanced Settings Section
    with st.expander("⚙️ Advanced: Hyperparameter Tuning"):
        st.markdown("""
        The model uses **TensorFlow** with these configurable parameters:

        | Parameter | Default | Range | Description |
        |-----------|---------|-------|-------------|
        | **Iterations** | 100 | 70-100 | More iterations = longer training but potentially better results |
        | **Features** | 100 | 70-100 | Number of latent features the model learns |
        | **Optimizer** | Adam | Adam/SGD/RMSprop | Algorithm used to minimize prediction error |

        **When to adjust:**
        - Poor predictions → Increase iterations
        - Slow training → Decrease iterations or features
        - Experimenting → Try different optimizers
        """)

    # FAQ Section
    with st.expander("❓ Frequently Asked Questions"):
        st.markdown("""
        **Q: Why don't I see recent movies?**

        A: The dataset (MovieLens) contains movies up to a certain date and isn't updated in real-time.

        ---

        **Q: What does the Magic Number do?**

        A: It's a random seed that determines which movies appear for rating. Same number = same movies.

        ---

        **Q: Why should I rate movies I've seen?**

        A: The algorithm learns your taste from your ratings. More honest ratings = better recommendations.

        ---

        **Q: What if I don't like the recommended movies?**

        A: Try rating more movies, selecting different genres, or adjusting the magic number to rate different films.
        """)

    # Notes Section
    with st.expander("📝 Notes & Disclaimer"):
        st.markdown("""
        - This application is for **educational purposes** only
        - The movie database may not include recently released films
        - Recommendations are generated by a machine learning model and may not always match your preferences perfectly
        - Feel free to experiment with different settings!
        """)

    st.divider()

    # Call to Action
    st.success("🎉 **Ready to start?** Head to the **Recommendation** page from the sidebar!")